services:
  - type: web
    name: tcg-sync
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SSH_HOST
        sync: false
      - key: SSH_PORT
        sync: false
      - key: SSH_USER
        sync: false
      - key: SSH_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PREFIX
        value: wpjx_
      - key: CATEGORY_SINGLES_ID
        value: "199"
